import type { Metadata } from "next";
import { Inter } from "next/font/google";
import "../globals.css";

const inter = Inter({ subsets: ["latin"] });

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="pt-br">
      <body className={inter.className}>
      <div className="min-h-screen grid grid-cols-2">
        <div className="h-full border-r border-foreground/5 bg-muted p-10 text-muted-foreground flex flex-col justify-between">
          <div>logo</div>
          <footer className="text-sm">
                  Burguer &Copy; - {new Date().getFullYear()}
          </footer>
        </div>

        <div className="flex flex-col items-center justify-center">
          {children}
       </div>
      </div>    
        </body>
    </html>
  );
}
